# Generated by Django 2.1.15 on 2020-05-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R1', models.CharField(max_length=20)),
                ('R2', models.CharField(max_length=20)),
                ('R3', models.CharField(max_length=20)),
                ('R4', models.CharField(max_length=20)),
                ('R5', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
