# Generated by Django 2.1.15 on 2020-05-09 03:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ping_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='R1',
            new_name='Router',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='R2',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='R3',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='R4',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='R5',
        ),
    ]
