# Generated by Django 2.1.15 on 2020-05-09 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ping_app', '0002_auto_20200509_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='description',
            new_name='Output',
        ),
    ]
