
---
- name: SHOW COMMANDS
  hosts: R1
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Run multiple commands on router
      ios_command:
       commands:
        - show ver
      vars:
       ansible_command_timeout: 40
      register: print_output
    - debug: var=print_output.stdout_lines
